apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-{{ .Values.name }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/project/wp-data-{{ .Values.name }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-{{ .Values.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi