apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-{{ .Values.name }}
  labels:
    app: mysql-{{ .Values.name }}
spec:
  replicas: 1
  serviceName: mysql-{{ .Values.name }}
  selector:
    matchLabels:
      app: mysql-{{ .Values.name }}
  template:
    metadata:
      labels:
        app: mysql-{{ .Values.name }}
    spec:
      containers:
      - name: database
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.mysqlpassword }}
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data-{{ .Values.name }}
          mountPath: /var/lib/mysql
      volumes:
          - name: mysql-data-{{ .Values.name }}
            persistentVolumeClaim:
              claimName: mysql-pvc-{{ .Values.name }}