apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-{{ .Values.name }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql-{{ .Values.name }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-{{ .Values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi