---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-{{ .Values.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-{{ .Values.name }}
  template:
    metadata:
      labels:
        app: wordpress-{{ .Values.name }}
    spec:
      containers:
        - name: wordpress
          image: wordpress:5.8.3-php7.4-apache
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-data-{{ .Values.name }}
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service-{{ .Values.name }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.mysqlpassword }}
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: mysql
      volumes:
        - name: wordpress-data-{{ .Values.name }}
          persistentVolumeClaim:
            claimName: wordpress-pvc-{{ .Values.name }}
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service-{{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: wordpress-{{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress-{{ .Values.name }}
spec:
  rules:
  - host: {{ .Values.domainname }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wordpress-service-{{ .Values.name }}
            port:
              number: 80